export const ERROR_MESSAGES = {
  INVALID_INPUT: "INVALID INPUT",
  NOT_FOUND: "NOT FOUND",
  SERVER_ERROR: "INTERNAL SERVER ERROR",
  FORBIDDEN: "FORBIDDEN",
  NOT_UPDATED: "NOT UPDATED",
  SERVER_RUN_FAILURE: "COULD NOT START SERVER",
};

export const SUCCESS_MESSAGES = {
  CREATED: "SUCCESSFULLY CREATED",
  UPDATED: "SUCCESSFULLY UPDATED",
  DELETED: "SUCCESSFULLY DELETED",
  CONNECTED: "CONNECTED TO POSTGRES",
  SERVER_RUN_SUCCESS: "SERVER STARTED ON PORT",
};
